const FEED_POSTS_LIMIT = 10;
const TOPIC_POSTS_LIMIT = 10;
const POST_COMMENTS_LIMIT = 15;
const COMMENT_REPLIES_LIMIT = 15;

module.exports = {
    FEED_POSTS_LIMIT,
    TOPIC_POSTS_LIMIT,
    POST_COMMENTS_LIMIT,
    COMMENT_REPLIES_LIMIT
};